// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-parceiros.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var list_parceiros_default = defineTool({
  name: "list_parceiros",
  title: "Listar cl\xEDnicas e parceiros",
  description: "Lista todas as cl\xEDnicas, laborat\xF3rios e parceiros conveniados da SBPM (Sociedade Beneficente da Pol\xEDcia Militar da Bahia). Inclui nome, especialidade, cidade, endere\xE7o, telefone e hor\xE1rio de funcionamento. Dados p\xFAblicos.",
  inputSchema: {
    cidade: z.string().optional().describe(
      "Filtrar por cidade (opcional). Ex.: 'Salvador', 'Feira de Santana'."
    ),
    especialidade: z.string().optional().describe(
      "Filtrar por especialidade (opcional). Ex.: 'Laborat\xF3rio', 'Ortopedia'."
    ),
    limit: z.number().int().optional().describe("N\xFAmero m\xE1ximo de resultados. Padr\xE3o: 100.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async ({ cidade, especialidade, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("clinicas_parceiros").select(
      "nome, especialidade, cidade, endereco, telefone, email, horario_funcionamento, logo_url"
    ).eq("ativo", true).order("cidade", { ascending: true }).order("nome", { ascending: true }).limit(Math.min(Math.max(limit ?? 100, 1), 500));
    if (cidade) query = query.ilike("cidade", `%${cidade}%`);
    if (especialidade)
      query = query.ilike("especialidade", `%${especialidade}%`);
    const { data, error } = await query;
    if (error) {
      return {
        content: [{ type: "text", text: `Erro: ${error.message}` }],
        isError: true
      };
    }
    const rows = data ?? [];
    const summary = rows.length === 0 ? "Nenhum parceiro encontrado com os filtros informados." : rows.map(
      (r) => `\u2022 ${r.nome} \u2014 ${r.especialidade ?? "\u2014"} \u2014 ${r.cidade}${r.telefone ? ` \u2014 \u260E ${r.telefone}` : ""}${r.endereco ? ` \u2014 ${r.endereco}` : ""}`
    ).join("\n");
    return {
      content: [
        {
          type: "text",
          text: `${rows.length} parceiro(s) encontrado(s):
${summary}`
        }
      ],
      structuredContent: { parceiros: rows, total: rows.length }
    };
  }
});

// src/lib/mcp/tools/list-cidades.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
var list_cidades_default = defineTool2({
  name: "list_cidades_atendidas",
  title: "Listar cidades atendidas",
  description: "Lista todas as cidades onde a SBPM possui cl\xEDnicas ou parceiros conveniados, com a contagem de parceiros por cidade. Dados p\xFAblicos.",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async () => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("clinicas_parceiros").select("cidade").eq("status", "ativo");
    if (error) {
      return {
        content: [{ type: "text", text: `Erro: ${error.message}` }],
        isError: true
      };
    }
    const counts = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      counts.set(row.cidade, (counts.get(row.cidade) ?? 0) + 1);
    }
    const cidades = Array.from(counts.entries()).map(([cidade, total]) => ({ cidade, total })).sort((a, b) => a.cidade.localeCompare(b.cidade));
    const summary = cidades.map((c) => `\u2022 ${c.cidade} \u2014 ${c.total} parceiro(s)`).join("\n");
    return {
      content: [
        {
          type: "text",
          text: `${cidades.length} cidade(s) atendida(s):
${summary}`
        }
      ],
      structuredContent: { cidades }
    };
  }
});

// src/lib/mcp/tools/canais-atendimento.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var canais = [
  {
    setor: "Previd\xEAncia",
    atendente: "Tina ou Val\xE9ria",
    whatsapp: "(71) 98549-6972"
  },
  {
    setor: "Assist\xEAncia \xE0 Sa\xFAde",
    atendente: "Rejane",
    whatsapp: "(71) 98794-3414"
  },
  {
    setor: "Assist\xEAncia \xE0 Sa\xFAde",
    atendente: "T\xE2nia",
    whatsapp: "(71) 99923-4059"
  },
  {
    setor: "Assist\xEAncia \xE0 Sa\xFAde",
    atendente: "Fabiane",
    whatsapp: "(71) 98146-8013"
  },
  {
    setor: "Assist\xEAncia \xE0 Sa\xFAde",
    atendente: "Tiago",
    whatsapp: "(71) 99634-0317"
  },
  {
    setor: "Centro M\xE9dico",
    atendente: "Javanete",
    whatsapp: "(71) 98791-2258"
  },
  {
    setor: "Posto Odontol\xF3gico",
    atendente: "M\xE1rcia",
    whatsapp: "(71) 98791-2263"
  }
];
var canais_atendimento_default = defineTool3({
  name: "list_canais_atendimento",
  title: "Listar canais de atendimento",
  description: "Lista os canais oficiais de atendimento da SBPM Bahia (WhatsApp por setor e atendente). Dados p\xFAblicos.",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: () => {
    const summary = canais.map(
      (c) => `\u2022 ${c.setor} \u2014 ${c.atendente}: ${c.whatsapp}`
    ).join("\n");
    return {
      content: [
        {
          type: "text",
          text: `Canais de atendimento SBPM:
${summary}

Website: https://www.sbpmbahia.com.br`
        }
      ],
      structuredContent: { canais, website: "https://www.sbpmbahia.com.br" }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iidqanlvudhrqobipimf";
var mcp_default = defineMcp({
  name: "sbpm-bahia-mcp",
  title: "SBPM Bahia \u2014 Parceiros e Atendimento",
  version: "0.1.0",
  instructions: "Ferramentas de consulta p\xFAblica da SBPM (Sociedade Beneficente da Pol\xEDcia Militar da Bahia): lista de cl\xEDnicas e parceiros conveniados por cidade e especialidade, cidades atendidas e canais oficiais de atendimento (WhatsApp por setor). N\xE3o exponha dados por usu\xE1rio.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_parceiros_default, list_cidades_default, canais_atendimento_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
